name: Documentation Build and Deploy CI

on:
  push:
    branches:
    - master
    - release/*
    paths:
    - 'docs/**'
    - '.github/workflows/docs.yml'
  pull_request:
    paths:
    - 'docs/**'
    - '.github/workflows/docs.yml'

jobs:

  build-docs:
    name: Build ESP-Docs
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build
      run: |
        sudo apt update
        sudo apt install python3-pip python3-setuptools
        # GitHub CI installs pip3 and setuptools outside the path.
        # Update the path to include them and run.
        cd ./docs
        PATH=/home/runner/.local/bin:$PATH pip3 install -r requirements.txt --prefer-binary
        PATH=/home/runner/.local/bin:$PATH SPHINXOPTS="-W" build-docs -l en
    - name: Archive Docs
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  deploy-preview-docs:
    name: Deploy Documentation
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Deploy Preview
      env:
        # Deploy to production server
        # DOCS_BUILD_DIR: "./docs/_build/"
        # DOCS_DEPLOY_PRIVATEKEY: ${{ secrets.DOCS_DEPLOY_KEY }}
        # DOCS_DEPLOY_SERVER: ${{ secrets.DOCS_SERVER }}
        # DOCS_DEPLOY_SERVER_USER: ${{ secrets.DOCS_SERVER_USER }}
        # DOCS_DEPLOY_PATH: ${{ secrets.DOCS_PATH }}
        # DOCS_DEPLOY_URL_BASE: ${{ secrets.DOCS_URL }}
        # Deploy to preview server
        
        DOCS_BUILD_DIR: "./docs/_build/"
        DOCS_PREVIEW_PRIVATEKEY: ${{ secrets.DOCS_KEY }}
        DOCS_PREVIEW_PATH: ${{ secrets.DOCS_PATH }}
        DOCS_PREVIEW_SERVER: ${{ secrets.DOCS_SERVER }}
        DOCS_PREVIEW_URL_BASE: ${{ secrets.DOCS_URL }}
        DOCS_PREVIEW_USER: ${{ secrets.DOCS_USER }}
      run: |
        sudo apt update
        sudo apt install python3-pip python3-setuptools
        source ./docs/utils.sh
        add_doc_server_ssh_keys $DOCS_PREVIEW_PRIVATEKEY $DOCS_PREVIEW_SERVER $DOCS_PREVIEW_USER
        export GIT_VER=$(git describe --always)
        echo "PIP install requirements..."
        pip3 install --user -r ./docs/requirements.txt
        echo "Building the Docs..."
        cd ./docs && build-docs -l en
        echo "Deploy the Docs..."
        deploy-docs
