name: ESP32 Arduino CI

on: [push]

jobs:

  build-arduino-0:
    name: Build Arduino IDE Tests 0
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        ESP32_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 0 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-1:
    name: Build Arduino IDE Tests 1
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 1 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-2:
    name: Build Arduino IDE Tests 2
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 2 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-3:
    name: Build Arduino IDE Tests 3
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 3 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-4:
    name: Build Arduino IDE Tests 4
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 4 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-5:
    name: Build Arduino IDE Tests 5
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 5 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-6:
    name: Build Arduino IDE Tests 6
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 6 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-7:
    name: Build Arduino IDE Tests 7
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 7 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-8:
    name: Build Arduino IDE Tests 8
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 8 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-9:
    name: Build Arduino IDE Tests 9
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 9 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-10:
    name: Build Arduino IDE Tests 10
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 10 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-11:
    name: Build Arduino IDE Tests 11
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 11 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-12:
    name: Build Arduino IDE Tests 12
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 12 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-13:
    name: Build Arduino IDE Tests 13
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 13 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-14:
    name: Build Arduino IDE Tests 14
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 14 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-15:
    name: Build Arduino IDE Tests 15
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 15 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-16:
    name: Build Arduino IDE Tests 16
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 16 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-17:
    name: Build Arduino IDE Tests 17
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 17 19
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-18:
    name: Build Arduino IDE Tests 18
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 18 19
    - name: Sketch Sizes
      run: cat size.log


  build-platformio:
    name: Build PlatformIO Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Python Wheel
      run: pip install wheel
    - name: Install GCC Toolchain
      run: cd tools && python get.py
    - name: Install PlatformIO
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-platformio.sh
    - name: Test PlatformIO
      run: ./tools/test-platformio.sh
