name: Pre-commit check

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  lint:
    if: contains(github.event.pull_request.labels.*.name, 'Status: Pending Merge')
    name: Checking if any fixes are needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42.0.2
      - name: Install and run pre-commit in changed files
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Push changes using pre-commit-ci-lite
        uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
