name: Sizes Results

on:
  workflow_run:
    workflows: [ESP32 Arduino CI]
    types:
      - completed

  workflow_dispatch:
env:
  # It's convenient to set variables for values used multiple times in the workflow
  SKETCHES_REPORTS_PATH: artifacts/sizes-report
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  PR_EVENT_PATH: artifacts/event-file/event.json

jobs:
  lib-test-results:
    name: Sizes Test Results
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download and Extract Artifacts
        run: |
          mkdir -p artifacts && cd artifacts
          mkdir -p sizes-report
          mkdir -p sizes-report/master
          mkdir -p sizes-report/pr
          artifacts_url=${{ github.event.workflow_run.artifacts_url }}
          gh api "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
          do
            IFS=$'\t' read name url <<< "$artifact"
            gh api $url > "$name.zip"
            unzip -j "$name.zip" -d "temp_$name"
            if [[ "$name" == *"master"* ]]; then
              mv "temp_$name"/* sizes-report/master
            elif [[ "$name" == *"pr"* ]]; then
              mv "temp_$name"/* sizes-report/pr
            else
              mv "temp_$name"/* sizes-report/
            fi
            rm -r "temp_$name"
          done
          echo "Contents of parent directory:"
          ls -R ..
    
      - name: Report results
        uses: P-R-O-C-H-Y/report-size-deltas@sizes
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}
          github-token: ${{ env.GITHUB_TOKEN }}
          pr-event-path: ${{ env.PR_EVENT_PATH }}
