name: Sizes Test
# Comment
# The workflow will run labeled pull requests
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

env:
  # It's convenient to set variables for values used multiple times in the workflow
  SKETCHES_REPORTS_PATH: sizes-report
  SKETCHES_REPORTS_ARTIFACT_NAME: sizes-report
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  compile-sketch:
    if: |
      contains(github.event.pull_request.labels.*.name, 'sizes_test')
    runs-on: ubuntu-latest

    env:
      REPOSITORY: |
        - source-path: '.'
          name: "espressif:esp32"

    strategy:
      matrix:
        target:
          - esp32
          - esp32s2
          - esp32c3
          - esp32s3
          - esp32c6
          - esp32h2

        include:
          - target: esp32
            fqbn: espressif:esp32:esp32
          - target: esp32s2
            fqbn: espressif:esp32:esp32s2
          - target: esp32c3
            fqbn: espressif:esp32:esp32c3
          - target: esp32s3
            fqbn: espressif:esp32:esp32s3
          - target: esp32c6
            fqbn: espressif:esp32:esp32c6
          - target: esp32h2
            fqbn: espressif:esp32:esp32h2


    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile sketch
        uses: P-R-O-C-H-Y/compile-sketches@sizes
        with:
          platforms: |
            ${{ env.REPOSITORY }}
          target: ${{ matrix.target }}
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            ${{ env.REPOSITORY }}
          use-json-file: false
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          enable-warnings-report: false
          cli-compile-flags: |
            - --warnings="all"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}-${{ matrix.target }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}

  report-comment:
    needs: compile-sketch  # Wait for the compile job to finish to get the data for the report
    runs-on: ubuntu-latest
    steps:
      # Check out repository
      - name: Checkout repository    
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: '0'

      # This step is needed to get the size data produced by the compile jobs
      - name: Download sketches reports artifact
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}-*
          merge-multiple: true
          path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Report results
        uses: P-R-O-C-H-Y/report-size-deltas@sizes
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}
