name: Hardware tests

on:
  workflow_call:
    inputs:
      type:
        type: string
        description: "Type of tests to run"
        required: true
      chip:
        type: string
        description: "Chip to run tests for"
        required: true

env:
  DEBIAN_FRONTEND: noninteractive

defaults:
  run:
    shell: bash

jobs:
  hardware-test:
    name: Hardware ${{ inputs.chip }} ${{ inputs.type }} tests
    runs-on: ["arduino", "${{ inputs.chip }}"]
    env:
      id: ${{ github.event.pull_request.number || github.ref }}-${{ github.event.pull_request.head.sha || github.sha }}-${{ inputs.chip }}-${{ inputs.type }}
    container:
      image: python:3.10.1-bullseye
      options: --privileged --device-cgroup-rule="c 188:* rmw" --device-cgroup-rule="c 166:* rmw"
    steps:
      - name: Clean workspace
        run: |
          rm -rf ./*
          rm -rf ~/.arduino/tests

      - name: Check if already passed
        id: cache-results
        if: github.event.pull_request.number != null
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: test-${{ env.id }}-results-hw
          path: |
            tests/**/*.xml
            tests/**/result_*.json

      - name: Evaluate if tests should be run
        id: check-tests
        run: |
          cache_exists=${{ steps.cache-results.outputs.cache-hit == 'true' }}
          enabled=true

          if [[ $cache_exists == 'true' ]]; then
            echo "Already ran, skipping"
            enabled=false
          fi

          echo "enabled=$enabled" >> $GITHUB_OUTPUT

      - name: Checkout user repository
        if: ${{ steps.check-tests.outputs.enabled == 'true' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Workaround for missing files in checkout
          sparse-checkout: |
            *

      # setup-python currently only works on ubuntu images
      # - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.0.4
      #   if: ${{ steps.check-tests.outputs.enabled == 'true' }}
      #   with:
      #     cache-dependency-path: tests/requirements.txt
      #     cache: 'pip'
      #     python-version: '3.10.1'

      - name: Install dependencies
        if: ${{ steps.check-tests.outputs.enabled == 'true' }}
        run: |
          pip install -U pip
          pip install -r tests/requirements.txt --extra-index-url https://dl.espressif.com/pypi
          apt update
          apt install -y jq

      - name: Get binaries
        if: ${{ steps.check-tests.outputs.enabled == 'true' }}
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: test-bin-${{ inputs.chip }}-${{ inputs.type }}
          path: |
            ~/.arduino/tests/${{ inputs.chip }}

      - name: List binaries
        if: ${{ steps.check-tests.outputs.enabled == 'true' }}
        run: |
          ls -laR ~/.arduino/tests

      - name: Run Tests
        if: ${{ steps.check-tests.outputs.enabled == 'true' }}
        run: |
          bash .github/scripts/tests_run.sh -c -type ${{ inputs.type }} -t ${{ inputs.chip }} -i 0 -m 1 -e

      - name: Upload ${{ inputs.chip }} ${{ inputs.type }} hardware results as cache
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: steps.check-tests.outputs.enabled == 'true' && github.event.pull_request.number != null
        with:
          key: test-${{ env.id }}-results-hw
          path: |
            tests/**/*.xml
            tests/**/result_*.json

      - name: Upload ${{ inputs.chip }} ${{ inputs.type }} hardware results as artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: test-results-hw-${{ inputs.chip }}-${{ inputs.type }}
          overwrite: true
          path: |
            tests/**/*.xml
            tests/**/result_*.json
